<?php

/**
 * @file
 * Allows site owner to add share buttons/recommendations on their website
 */

/**
 * Implementation of hook_menu()
 *
 * Establish a link to the Shareaholic Admin settings page
 *
 * @return The menu structure containing link to settings page
 */
function shareaholic_menu() {
  // Path to the shareaholic settings page
  $items['admin/config/content/shareaholic/settings'] = array(
    'title' => 'Shareaholic Settings',
    'description' => 'Configure the Shareaholic share buttons on your site',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('shareaholic_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}


/**
 * Form builder for the shareaholic settings page
 *
 * @return The form structure for the settings page
 */
function shareaholic_admin_settings() {
  $module_path = drupal_get_path('module', 'shareaholic');

  $form['name'] = array(
    '#title' => t('Shareaholic Settings'),
    '#type' => 'fieldset',
    '#description' => t('Configure your Shareaholic Settings')
  );

  $form['#attached']['css'] = array(
    $module_path . '/assets/css/main.css' => array('group' => CSS_DEFAULT)
  );
  $form['#attached']['js'] = array(
    $module_path . '/assets/js/jquery_custom.js' => array('group' => JS_DEFAULT),
    $module_path . '/assets/js/main.js' => array('group' => JS_DEFAULT)
  );

  $form['#theme'] = 'shareaholic_admin_settings';
  return $form;
}


/**
 * Implements hook_theme().
 * Add the theme (JS, CSS) files for the shareaholic admin settings page
 *
 * @return array An array that includes theme rules for the settings page
 */
function shareaholic_theme() {
  return array(
    'shareaholic_admin_settings' => array(
      'render element' => 'form',
      'template' => 'templates/shareaholic_admin_settings',
    ),
  );
}
